source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'omnibus', '~> 6.1.4'
gem 'omnibus-software', github: 'chef/omnibus-software', ref: 'ae2a2f1cae3e8d80197a1cac5311b910300a53ff'
