source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'omnibus', '~> 5.5.0'
gem 'omnibus-software', github: 'chef/omnibus-software', ref: '91d716b2f88127e0b1f742b98c63e18119498af3'
