FROM centos:7

RUN yum install -y gnupg-agent gnupg2 rpm-sign expect

RUN echo "%_signature gpg" > ~/.rpmmacros
RUN echo "%_gpg_name 7CC06B54" >> ~/.rpmmacros
RUN echo "%__gpg_check_password_cmd /bin/true" >> ~/.rpmmacros
RUN echo '%__gpg_sign_cmd     %{__gpg} \
  gpg --batch --no-verbose --no-armor \
  --passphrase-file /tmp/passphrase_file \
  %{?_gpg_digest_algo:--digest-algo %{_gpg_digest_algo}} \
  --no-secmem-warning \
  -u "%{_gpg_name}" -sbo %{__signature_filename} %{__plaintext_filename}' >> ~/.rpmmacros


CMD \
  gpg-agent --daemon --pinentry-program=/usr/bin/pinentry-curses \
            --use-standard-socket; \
  while gpg-connect-agent /bye; do \
    sleep 2; \
  done
