FROM debian:jessie

RUN \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y dpkg-sig gnupg-agent gnupg2 && \
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD \
  gpg-agent --daemon --pinentry-program=/usr/bin/pinentry-curses \
            --use-standard-socket; \
  while gpg-connect-agent /bye; do \
    sleep 2; \
  done
