#!/bin/bash
#
# Perform necessary crystal setup steps
# after package is installed.
#

INSTALL_PATH=/usr
if [ "$(uname)" = "Darwin" ] && [ "$(uname -r|cut -f1 -d.)" -ge 15 ]; then
	INSTALL_PATH=/usr/local
fi

ln -nfs /opt/crystal/bin/crystal ${INSTALL_PATH}/bin/crystal
ln -nfs /opt/crystal/embedded/bin/shards ${INSTALL_PATH}/bin/shards

exit 0
